name: Deploy to Openshfit 
on: 
    push: 
        branches: 
            - master
jobs:
    deploy:
        name: deploy-job
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v6
        - name: List the files in the reppository
          run: |
            echo "Checking out code..."
            ls -la
        - name: Install oc client 
          uses: redhat-actions/openshift-tools-installer@v1
          with:
            oc: 'latest'
        - name: Verify OC Client Version 
          run: |
                echo "Verifying OC client installation..."
                oc version --client
        - name: Login to Openshift cluster 
          run: |
            echo "************** Logging in to OpenShift cluster *************"
            oc login \
              --server=${{ secrets.OC_SERVER }} \
              --token=${{  secrets.OC_TOKEN }} \
              --insecure-skip-tls-verify=true
        - name: Test List of Pods
          run: |
            echo "Testing OC client by listing pods in the cluster..."
            oc get pods -n i27-github-actions-demo
        - name: Trigger S2I  Build 
          run: 
            oc start-build i27academy-demo-app -n i27-github-actions-demo
        - name: Verify Deployment 
          run: | 
            oc rollout status deployment/i27academy-demo-app --timeout=120s -n i27-github-actions-demo
            echo "*********** Deployment Succesfull! , App is live in Openshift"
          









           # oc login --token=$SA_TOKEN --server=https://api.i27-cluster.i27openshift.com:6443
        #   run: |
        #     echo "Installing oc client..."
        #     curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz | tar xz -C /usr/local/bin --no-same-owner --strip-components=1 oc kubectl